# VSync & Frame Control
#dxgi.syncInterval = 1
#no sync
dxgi.syncInterval = 0
dxgi.maxFrameRate = 300
#dxvk.enableGraphicsPipelineLibrary = False
dxgi.maxFrameLatency = 1

# AMD RDNA2 Optimizations
#dxvk.useRawSsbo = True
#dxvk.enableDescriptorHeap = Auto
#dxvk.enableMemoryDefrag = False
#dxvk.enableDescriptorBuffer = False

# Latency
#dxvk.latencySleep = Auto
